Converting Rasa-Demo to 2.0 Format
RasaHQ/rasa-demo pull request #566
Opened 2020-08-24 18:29 UTC by b-quachtran

2020-08-24 18:38 UTC, b-quachtran commented
@melindaloubser1 I've converted the NLU files to 2.0 (only thing missing is the lookup table file definition in the training data, since there doesn't seem to be support for that right now). 

I've put down a few to-do tasks, lmk which ones you can take up and if there's anything missing from that list.

2020-08-24 21:11 UTC, melindaloubser1 commented
Nice! The lookup tables are included inline in the yaml file now, no more txt files seperately. I can add those. I guess it makes sense to work in the order of the todos since they each depend on the previous to some degree. Would it be more helpful if I took an earlier one or a later one?

2020-08-25 15:27 UTC, b-quachtran commented
Yah, can you take on the story conversion and test out the Core converter tool? I can work on the Forms migration in parallel since those changes will mostly be in the domain file.

2020-08-25 22:17 UTC, melindaloubser1 commented
sounds good!

2020-09-21 22:47 UTC, b-quachtran commented
Data validation CI check is failing because of a bug with the new ResponseSelector format (https://github.com/RasaHQ/rasa/issues/6728)

2020-09-28 14:45 UTC, melindaloubser1 commented
@b-quachtran I'm seeing errors running `rasa data validate` - do you also?
A q about the test conversations: we really should have more test convos, but since we don't, how did you go about testing it all together?

2020-09-28 16:46 UTC, b-quachtran commented
@melindaloubser1 Yeah I created an [issue](https://github.com/RasaHQ/rasa/issues/6728) for the `rasa data validate` bug. I've been testing locally through the shell but that's an action item for sure. I'll work on adding more test cases and update the ConveRT configs as well.

2020-09-29 16:51 UTC, melindaloubser1 requested changes
Few things aren't working:
-  Error when retrieving response selector intents:
 `Couldn't create message for response 'utter_out_of_scope'`
Is this part of the issue above?

- Evaluating all training stories shows we must have conflicts somewhere:
```
Evaluation Results on CONVERSATION level:
 Correct:          425 / 438
 F1-Score:         0.985
 Precision:        1.000
 Accuracy:         0.970
 In-data fraction: 0.927
Stories report saved to results/story_report.json.
Evaluation Results on ACTION level:
 Correct:          5883 / 5898
 F1-Score:         0.998
 Precision:        0.998
 Accuracy:         0.997
 In-data fraction: 0.927
```

General things:
-  we should use rules wherever it makes sense (i.e. for all the single-turn interactions). This especially since users will use this repo as an example of how to migrate a bot to 2.0, and we want to use our own best practices =)
- we should add test conversations for all our main skills. I know this is a lot on top of all the changes, but it will really be worth it when making changes in the new format, since we're more likely to make mistakes because we're less used to it.

2020-09-29 16:54 UTC, melindaloubser1 commented
We could potentially wait until sara is deployed in 2.0, then use rasa X to save test convos in the new format... but then we'd have to ship it without checking. I'll get started with a list of flows to add tests for so long.

2020-09-29 17:12 UTC, melindaloubser1 commented
Feel free to edit these lists

Tests to add (general categories):
- [ ] sales form
- [ ] getting started 
- [ ] newsletter form
- [ ] faqs (esp. the ones with slots)
- [ ] general questions (why_rasa, ask_how_contribute, etc.)
- [ ] handoff
- [ ] chitchat 
- [ ] out of scope
- [ ] fallback

Things that should probably have a rule associated with them (multiturn stories remain):
- sales form
- newsletter form
- ask_how_contribute
- ask_question_in_forum
- ask_when_next_event
- ask_which_events
- ask_why_contribute
- canthelp
- feedback
- greet
- technical_question
- thank
- why_rasa
- fallback
- source_code
- restart
- nlu_generation_tool_recommendation
- human_handoff

2020-10-06 23:15 UTC, b-quachtran commented
@melindaloubser1 Training using Vova's branch https://github.com/RasaHQ/rasa/tree/fix-incomplete-rules works, so you can use that to test until the fix is packaged with the next 2.0 release

2020-10-07 13:39 UTC, melindaloubser1 reviewed
just leaving these comments for now

2020-10-07 19:02 UTC, b-quachtran commented on tests/test_stories.yml
> +# - story: technical_question - no docs_found
Yep, this can be removed

2020-10-07 19:03 UTC, b-quachtran commented on tests/test_nlu.yml
> +    - of course
I think we should keep the NLU tests, but I'll work on getting it up to date

2020-10-07 20:45 UTC, b-quachtran commented on data/rules/fallback.yml
> +      - active_loop: action_two_stage_fallback
It should do a revert by default after the correct intent is selected in the fallback, so I don't think so.

2020-10-07 20:47 UTC, melindaloubser1 commented on data/rules/fallback.yml
> +      - active_loop: action_two_stage_fallback
interesting. It doesn't need a `wait_for_user_input: false` either? Testing it atm

2020-10-12 19:16 UTC, b-quachtran commented
@melindaloubser1 The rephrase issue with the Two Stage Fallback turned out to be a bug in the custom action code. It should be working now, although that open issue with `nlu_fallback` showing up as the predicted intent is still happening.

2020-10-13 14:16 UTC, melindaloubser1 commented
Look at that passing CI 🚀🚀

2020-10-13 14:19 UTC, melindaloubser1 commented
I am wondering why NLU results have decreased so much since last run here:  https://github.com/RasaHQ/rasa-demo/pull/552#issuecomment-652013024 - did we lose any data in this process?

2020-10-13 15:16 UTC, b-quachtran commented
> I am wondering why NLU results have decreased so much since last run here: [#552 (comment)](https://github.com/RasaHQ/rasa-demo/pull/552#issuecomment-652013024) - did we lose any data in this process?

It looks like nlu_fallback is causing quite a bit of confusion for the intent cross validation, which is probably related to that open issue.

2020-10-13 16:49 UTC, melindaloubser1 commented
hmmm I think fallback_classifier needs to somehow get ignored during evaluation.

2020-10-14 17:23 UTC, b-quachtran commented
> hmmm I think fallback_classifier needs to somehow get ignored during evaluation.

That seems like a bug, I'm following up [here](https://github.com/RasaHQ/rasa/issues/6285). 

Is there anything else that's causing a problem with Sara 2.0 in your testing?

2020-10-16 10:56 UTC, melindaloubser1 commented
Sorry just saw the q now - The many checkpoints in stories look like a potential converter bug, am trying to resolve them; also interruptions in forms weren't quite working, the rules for faqs specified `conversation_start: true` which I'm removing

2020-10-16 21:49 UTC, b-quachtran commented
@melindaloubser1 I'm seeing a bunch of story contradictions being thrown during training, working through them at the moment but probably won't be resolved until Monday.

2020-10-20 07:58 UTC, b-quachtran commented
@melindaloubser1 Context switching is working now and the rule conflicts are resolved. Can you review when you get a chance?

2020-10-20 08:44 UTC, melindaloubser1 commented
Will do. Have we opened an issue for the nlu_fallback confusion during evaluation anywhere?

2020-10-20 15:47 UTC, b-quachtran commented
Yeah it's in the discussion in the issue Akela made [here](https://github.com/RasaHQ/rasa/issues/6285)

2020-10-22 14:30 UTC, koaning commented
Just to make folks aware. I just tried running `rasa nlu test` locally and I'm seeing some strange bugs. 

```
> rasa test nlu --config config-templates/just-sparse.yml --cross-validation --runs 1 --folds 2 --out gridresults/just-sparse
...
...
...
Traceback (most recent call last):
  File "/home/vincent/Development/rasa-demo/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/cli/test.py", line 159, in run_nlu_test
    perform_nlu_cross_validation(config, nlu_data, output, vars(args))
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/test.py", line 276, in perform_nlu_cross_validation
    data, folds, nlu_config, output, **kwargs
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/test.py", line 1687, in cross_validate
    train,
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/test.py", line 1595, in combine_result
    ) = compute_metrics(interpreter, data)
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/test.py", line 1776, in compute_metrics
    interpreter, training_data
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/test.py", line 1310, in get_eval_data
    result = interpreter.parse(example.get(TEXT), only_output_properties=False)
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 398, in parse
    component.process(message, **self.context)
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/selectors/response_selector.py", line 382, in process
    self._resolve_intent_response_key(top_label) or top_label[INTENT_NAME_KEY]
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/nlu/selectors/response_selector.py", line 363, in _resolve_intent_response_key
    search_key = util.template_key_to_intent_response_key(key)
  File "/home/vincent/Development/rasa-demo/venv/lib/python3.7/site-packages/rasa/shared/nlu/training_data/util.py", line 145, in template_key_to_intent_response_key
    return template_key.split(UTTER_PREFIX)[1]
```

It's suggested [here](https://forum.rasa.com/t/rasa2-0-0rc2-no-configuration-file-was-provided-to-the-trainingdataimporter/35381) that it might be due to a data conversion error so I figured I'd check in.

2020-10-26 15:24 UTC, melindaloubser1 commented
@koaning I think this might be an environment thing, I'm not seeing that on 2.0.2

2020-10-26 15:29 UTC, melindaloubser1 commented on data/nlu/nlu.yml
> +    - Any other event like rasa meetup in future?
```suggestion
    - Any other event like rasa meetup in future?
    - Does Rasa host any events?
```

2020-10-26 15:30 UTC, melindaloubser1 approved these changes
besides the false positive story conflicts (`after ...` and `after action_listen` ) this looks good!

2020-10-30 04:33 UTC, merged