update to 2.6.1/0.39.3
RasaHQ/rasa-demo pull request #642
Opened 2021-05-14 10:18 UTC by melindaloubser1

Update deployment to rasa 2.6.1 and rasa x 0.39.3

2021-05-17 10:19 UTC, hsm207 approved these changes

2021-05-17 11:18 UTC, hsm207 requested changes
Need to fix these contracting rules:

```
InvalidRule: 
Contradicting rules or stories found 🚨

- the prediction of the action 'utter_switch_dialogflow' in story 'why rasa 4' is contradicting with rule(s) 'why rasa 2, why rasa 3' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_switch_luis' in story 'why rasa 3' is contradicting with rule(s) 'why rasa 2, why rasa 4' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_switch_dialogflow' in story 'why rasa 8' is contradicting with rule(s) 'why rasa 2, why rasa 3' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_switch_luis' in story 'why rasa 7' is contradicting with rule(s) 'why rasa 2, why rasa 4' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_switch_luis' in rule 'why rasa 3' is contradicting with rule(s) 'why rasa 2, why rasa 4' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_switch_dialogflow' in rule 'why rasa 4' is contradicting with rule(s) 'why rasa 2, why rasa 3' which predicted action 'utter_ask_more'.
- the prediction of the action 'utter_explain_core' in rule 'explain Core' is contradicting with rule(s) 'explain X, explain NLU' which predicted action 'utter_explain_nlu'.
- the prediction of the action 'utter_explain_x' in rule 'explain X' is contradicting with rule(s) 'explain NLU, explain Core' which predicted action 'utter_explain_nlu'.
Please update your stories and rules so that they don't contradict each other.
You can find more information about the usage of rules at https://rasa.com/docs/rasa/rules. 
```

2021-05-17 13:04 UTC, melindaloubser1 commented
Ja, it's weird that this started happening only on this version 😬

2021-05-19 11:05 UTC, erohmensing approved these changes

2021-05-19 12:08 UTC, merged